//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public Blog()
        {
            this.BlogPosts = new HashSet<BlogPost>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<BlogPost> BlogPosts { get; set; }
        public virtual BlogSettings BlogSettings { get; set; }
    }
}
