//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Blogs = new HashSet<Blog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Gender Gender { get; set; }
    
        public virtual ICollection<Blog> Blogs { get; set; }
    }
}
